@url=http://localhost:5557

### GET JOBS
GET {{url}}/jobs

### SHOW ONE JOB
GET {{url}}/jobs/2

### POST JOBS
POST {{url}}/jobs
content-type: application/json

{
    "jobTitle": "Ruby Developer1",
    "description": "This is a good Ruby Job."
}

